/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedSimulationRouteImport } from './routes/_authenticated/simulation'
import { Route as AuthenticatedContactsIndexRouteImport } from './routes/_authenticated/contacts/index'
import { Route as AuthenticatedContactsStudentIdRouteImport } from './routes/_authenticated/contacts/$studentId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimulationRoute = AuthenticatedSimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsIndexRoute =
  AuthenticatedContactsIndexRouteImport.update({
    id: '/contacts/',
    path: '/contacts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactsStudentIdRoute =
  AuthenticatedContactsStudentIdRouteImport.update({
    id: '/contacts/$studentId',
    path: '/contacts/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/simulation': typeof AuthenticatedSimulationRoute
  '/contacts/$studentId': typeof AuthenticatedContactsStudentIdRoute
  '/contacts/': typeof AuthenticatedContactsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/simulation': typeof AuthenticatedSimulationRoute
  '/': typeof AuthenticatedIndexRoute
  '/contacts/$studentId': typeof AuthenticatedContactsStudentIdRoute
  '/contacts': typeof AuthenticatedContactsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/simulation': typeof AuthenticatedSimulationRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/contacts/$studentId': typeof AuthenticatedContactsStudentIdRoute
  '/_authenticated/contacts/': typeof AuthenticatedContactsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/crm'
    | '/simulation'
    | '/contacts/$studentId'
    | '/contacts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/crm'
    | '/simulation'
    | '/'
    | '/contacts/$studentId'
    | '/contacts'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/crm'
    | '/_authenticated/simulation'
    | '/_authenticated/'
    | '/_authenticated/contacts/$studentId'
    | '/_authenticated/contacts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulation': {
      id: '/_authenticated/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof AuthenticatedSimulationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts/': {
      id: '/_authenticated/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AuthenticatedContactsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts/$studentId': {
      id: '/_authenticated/contacts/$studentId'
      path: '/contacts/$studentId'
      fullPath: '/contacts/$studentId'
      preLoaderRoute: typeof AuthenticatedContactsStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedSimulationRoute: typeof AuthenticatedSimulationRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedContactsStudentIdRoute: typeof AuthenticatedContactsStudentIdRoute
  AuthenticatedContactsIndexRoute: typeof AuthenticatedContactsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedSimulationRoute: AuthenticatedSimulationRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedContactsStudentIdRoute: AuthenticatedContactsStudentIdRoute,
  AuthenticatedContactsIndexRoute: AuthenticatedContactsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
